In [1]:
import numpy as np
from LinClass import LinClass

In [2]:
X = np.load('M1Data/x_test.npy', allow_pickle = True)
Y = np.load('M1Data/y_test.npy', allow_pickle = True)
names = np.load('M1Data/names.npy', allow_pickle = True)

In [3]:
X_train, X_test, Y_train, Y_test = X[:int(len(X)/3 * 2)], X[int(len(X)/3*2):], Y[0:int(len(Y)/3*2)], Y[int(len(Y)/3*2):]

In [4]:
#too many zeros on some columns, standard deviation is guranteed to be 0 in some columns so standardizing predictors makes no sense
#we can't really do linregg

In [5]:
M1Classifications = LinClass(X_train, Y_train, np.array(['First Round', 'Second Round', 'Third Round', 'Semi Semi Finals', 'Semi Finals', 'Finals', 'Victory']))

In [6]:
M1Classifications.setProbabilities()
print(M1Classifications.probabilities)
M1Classifications.setMeans()
print(M1Classifications.means)
M1Classifications.setLinearCovariance()
print(M1Classifications.linearCovariance)
M1Classifications.setQuadraticCovariance()
print(M1Classifications.quadraticCovariance)

[6.42397943e-01 2.52732240e-01 6.66184507e-02 2.71616843e-02
 7.23240116e-03 3.45548055e-03 4.01800064e-04]
[[2.014e+03 2.000e+00 1.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 [2.015e+03 2.000e+00 1.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 [2.013e+03 2.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 ...
 [2.013e+03 2.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 [2.014e+03 2.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 [2.013e+03 2.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]]
[[ 1.19991155e+01  1.01310606e-02  4.69486210e-01 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 1.01310606e-02  4.88863874e-02 -2.41215727e-02 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 4.69486210e-01 -2.41215727e-02  6.05049449e-01 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00

In [7]:
correct = 0
total = 0
for ii in range(len(X_test)):
    guess = M1Classifications.linearDiscriminantAnalysisSolve(X_test[ii])
    answer = M1Classifications.indicators[np.nonzero(Y_test[ii])[0]]
    print(guess)
    print(answer)
    if guess == answer:
        correct +=1
    total +=1
print(correct/total)

[[ 9.95880015e-01  5.90413030e-02  5.44521355e-02 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 6.32943055e-04  2.23704079e-02  2.62372930e-02 ... -1.47626425e-32
   1.36348119e-32 -4.94629311e-32]
 [ 4.32699029e-02 -5.88325656e-01 -1.74727287e-01 ...  2.90120270e-32
   9.16287107e-33 -8.14090917e-32]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]]
[1.20923934e+01 1.33776192e+00 4.02659480e-01 3.60405509e-01
 2.25480992e-01 2.03279230e-01 1.57883765e-01 1.33481361e-01
 9.91668499e-02 7.54060159e-02 6.57142818e-02 6.10448261e-02
 5.96242769e-02 5.38603094e-02 4.78428864e-02 4.27550435e-02
 3.94836476e-02 3.44489890e-02 3.09754306e-02 2.80309686e-02
 2.49748645e-02 2.19797387e-02 2.07907116e-02 1.99158789e-0

C:\Users\hhong\Documents\MLPackage\LinClass\__init__.py:102: RuntimeWarning: divide by zero encountered in true_divide
  invSqrtD = np.diag(np.sqrt(1/d))


ValueError: shapes (461,461) and (12444,461) not aligned: 461 (dim 1) != 12444 (dim 0)